# Install the package and run all tests except the graph-cut ones
# Triggers on: All PRs that are mergable, but not for draft PRs
# Triggers on: all published releases (incl pre-releases)

name: Run tests (wo graphcut)

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  release:
    types: [published]

permissions:
  contents: read

jobs:
  run-tests:
    if: github.event.pull_request.draft == false

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install with test dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[test]
      - name: Test with pytest
        run: |
          pytest tests/features_/*
          pytest tests/filter_/*
          pytest tests/io_/*
          pytest tests/metric_/*
